mysql:
  host: localhost
  port: 3306
  username: root
  password: root
  database: trauma
nacos:
  # Nacos server address
  server-addr: 127.0.0.1:8848
  # Bug: set it as "public" can not
  namespace: ""
  group: DEFAULT_GROUP
  data-id: application-{}.yaml
server:
  # Listen host
  host: 127.0.0.1
  # Listen port
  port: 7070
  # Service name for register to nacos
  name: "sea-orm-demo"
  # Trace = 0
  # Debug = 1,
  # Info = 2,
  # Warn = 3,
  # Error = 4,
  log-level: 2
actix:
  workers: 10
